### ISSUE TITLE
[FO4] Access violation when making smashed patch

### ISSUE THREAD

**Issue by Woffingshire** [matortheeternal/smash#207] opened 2018-07-07 22:03 UTC
So I've been using Mator smash for FO4 for quite a while now and I just added some new mods and made another smash patch, however this time when I make a smash patch it gets to the unofficial FO4 patch, something it had no issue with in the past, and then stops working due to an access violation.
Here is the message in full:

Building patch: Smashed Patch
 
Patch is using plugin: Smashed Patch.esp
Adding masters...
Done adding masters
 
Processing files
Processing DLCRobot.esm
Processing DLCworkshop01.esm
Processing DLCCoast.esm
Processing DLCworkshop02.esm
Processing DLCworkshop03.esm
Processing DLCNukaWorld.esm
Processing Unofficial Fallout 4 Patch.esp
Failed to patch Smashed Patch, Access violation at address 5711A481. Write of address 8E209803
 

All done!

Removing the plugin from the patch lets it carry on as normal until it reaches Combat Zone Restored when the exact same thing happens. I have about 90 plugins active if that makes any difference.

Usually after doing that, if I try to do anything else in the program I get and error saying this "Access Violation at address 00443E71 in module 'MatorSmash.exe' Read of address 000000000"

**Comment by Woffingshire** [comment] 2018-07-07 22:12
Usually after doing that, if I try to do anything else in the program I get and error saying this "Access Violation at address 00443E71 in module 'MatorSmash.exe' Read of address 000000000"

**Comment by Woffingshire** [comment] 2018-07-07 22:54
Okay so I found what the issue is. Its a mod called Combat Zone Restored. When its loaded to be patched at the same time as the Unofficial Patch, the patcher stops working on the unofficial patch. If its loaded to be patched without the unofficial patch, it stops working when it gets to Combat Zone Restored. Either way, it really hates that one particular mod.

**Comment by matortheeternal** [comment] 2018-07-11 23:18
Duplicate of #183

**Closed by matortheeternal** 2018-07-11 23:18 UTC
Labels: bug

**Comment by ghost** [comment] 2019-03-19 06:00
@Woffingshire That's so weird! But thank you so much~! Worked for me as well.
