### ISSUE TITLE
[FO4] Smash causing some ammo names to be replaced with "<Error: No Strings file found>"

### ISSUE THREAD

**Issue by Woffingshire** [matortheeternal/smash#210] opened 2018-07-11 21:08 UTC
![smash bug](https://user-images.githubusercontent.com/20581364/42599356-e230f8ba-8556-11e8-8249-563cda3e7e40.PNG)

**Comment by matortheeternal** [comment] 2018-07-11 23:08
Duplicate of #189.

**Closed by matortheeternal** 2018-07-11 23:08 UTC
