### ISSUE TITLE
Changing plugin to Skip is not being recognized during patch

### ISSUE THREAD

**Issue by EssArrBee** [matortheeternal/smash#148] opened 2017-06-11 01:13 UTC
First, set a list of mods to Bash.All. Returned to rerun the patch without two plugins and set both to Skip. After running the patcher neither mod was skipped in the resulting patch. Restarting Smash showed both plugins set back to Bash.All.

**Comment by matortheeternal** [comment] 2017-07-17 20:12
Duplicate of #133 ?

**Comment by psolyca** [comment] 2017-12-13 10:01
I have tried to look at this one but it seems that patch do not take plugin with Skip setting.
@EssArrBee could you provide more information ?

**Closed** 2018-05-02 02:43 UTC
Labels: duplicate, verification needed
